### ISSUE TITLE
repeated value in glyphs enum

### ISSUE THREAD

**Issue by rvilarl** [vexflow/vexflow#109]
git/vexflow/src/glyphs.ts
  3591:3  error  Duplicate enum member value 𝆹  @typescript-eslint/no-duplicate-enum-values

**Comment by rvilarl** [comment]
@ronyeh can you look into that I did not find the constant in smufl.org

**Comment by ronyeh** [comment]
Indeed one of the smufl alternate codepoints is a repeat of another smufl codepoints. Since we stored it in an enum, it triggers this linting error. I am not sure if the smufl spec has an error or not, since the glyphs are slightly different. 

Or we can just add an eslint ignore for this special case.

**Comment by rvilarl** [comment]
I am not able to find **mensuralBlackSemibrevisVoidAlternate** in smufl.org.

**Comment by ronyeh** [comment]
In glyphnames.json: https://raw.githubusercontent.com/w3c/smufl/gh-pages/metadata/glyphnames.json

There is a `mensuralBlackSemibrevisVoid`.

```json
"mensuralBlackSemibrevisVoid": {
  "alternateCodepoint": "U+1D1B9",
  "codepoint": "U+E957",
  "description": "Black mensural void semibrevis"
},
```

The `vexflow/tools/fonts/glyph_codes.js` script extracts all SMuFL code points. When it discovers an alternate codepoint, it adds a suffix 'Alternate' to the smufl friendly name, since we cannot have multiple enum keys with the same exact name.

If you think alternateCodepoints are not necessary to support, we can just comment out this block:

Lines 67-69:
```
    if (glyphInfo.alternateCodepoint) {
      addEntry(smuflCodeName, glyphInfo.alternateCodepoint, glyphInfo.description, 'Alternate');
    }
```

That should solve the duplicate enum value problem, because the code point is shared with mensuralWhiteSemibrevis (alternate).

**Comment by rvilarl** [comment]
@ronyeh have you looked if any of the fonts (ie Bravura), implement the alternate codes?

**Comment by ronyeh** [comment]
I believe Bravura implements every glyph in the SMuFL specification, but
you can check a few of the alternate codes (by sticking the unicode in an
Element to see if it renders).

**Comment by rvilarl** [comment]
@ronyeh yes, they are implemented in Bravura!, We need them!

**Comment by ronyeh** [comment]
OK, so we can reintroduce the alternative code points.

1) We can remove the eslint rule that throws an error for duplicate enum values.
2) Or instead of an enum, we can export separate strings from the module. This is probably the most flexible solution.

**Comment by rvilarl** [comment]
At one stage we will also get duplicates with the vexflow specific Codes.
