### ISSUE TITLE
Remove src and others from packaged version

### ISSUE THREAD

**Issue by mscuthbert** [vexflow/vexflow#181]
Vexflow currently publishes both types and the src .ts files. 

TypeScript (w/ behavior that seems almost like a bug to me), will check any .ts files in node_modules even if specifically excluded if they are imported into the package.  (https://github.com/microsoft/TypeScript/issues/47387 for MS's response and https://github.com/juanjoDiaz/streamparser-json/issues/26 for an easier introduction).

A problem happens when Vexflow is imported into a TypeScript project with stricter tsconfig.json settings than Vexflow.  For instance, I have a project that uses `noImplicitOverride` so all overrides have to have `override` before them.  Typescript compilation will see that Vexflow's  types.d.ts file points to the original .ts files and therefore check them and give hundreds of "override missing" errors.

My current solution is to remove the things from Vexflow's node_modules package that are not needed:

```bash
rm -rf node_modules/vexflow/entry
rm -rf node_modules/vexflow/releases
rm -rf node_modules/vexflow/src
rm -rf node_modules/vexflow/tests
```

Better however is to just not publish these since they are only needed by developers.

(Issue in 4.2.3 also)

**Comment by ronyeh** [comment]
I haven't had a chance to think through your proposal, but I feel like I had a good reason to include the original TS source files.... Are there situations where the bundler or IDE will prefer to use the TS files instead of the the compiled libraries? Maybe webpack or esbuild can do a better job building a TS-only app and dropping dead VexFlow-related code if it is not used by the app?

Are there any other solutions to your problem? I understand it's annoying to have to remove those redundant files from your project.

What do other TS projects do? 

When I was working on the build process, I was inspired by how Tone.js laid out their NPM package. See: https://unpkg.com/browse/tone@14.7.77/

They do include the TS source files under the Tone/ folder.

But it's possible that including the source is not "the right way" to publish on NPM. (I'm not an expert here.) We could always have developers directly pull from our GitHub repo if they need to build directly against the TS source code.

**Comment by mscuthbert** [comment]
I looked at the Webpack module to see that the .ts files were not being included. I figure that if anyone would know how best to package a module it would be them. 

I had hoped that packaging the tsconfig.json file would be enough to fix the problem but alas it wasn't. 

To develop the module one should really clone it. I don't think we want to make the NPM version something to encourage people to develop from. That's why examples, demos, tests, etc are generally not included in NPM pubs. 

Removing these things from the music21j package had the bonus that the NPM package went from 8MB compressed (35MB expanded) to 1MB compressed (8MB expanded). If you want to be able to debug code in the browser though it is important to generate a source map for each entry point and to package that. With the source map the whole library is still available to debugging.

**Comment by AaronDavidNewman** [comment]
Good idea.  I think it makes sense to include the js monolith, source map and type files in the npm package.

**Comment by ronyeh** [comment]
I did some more research and the biggest benefit from including the `*.ts` files in the NPM distribution is related to debugging. For example, VS Code or other debuggers can link directly to the TS source when you ctrl+click or command+click on a class name. The TS files can also be linked to from source maps.

So since the benefit of **NOT including** TS files is to improve the normal development workflow, and the benefit of **including** is to occasionally help with debugging, I agree with you that not including is the better choice most of the time.

I'll submit a PR for this.

**Comment by rvilarl** [comment]
Sorry for locking, unintended and thanks Ron!

**Comment by mscuthbert** [comment]
I think that if you include the map files for the compiled js then at least Google chrome can allow debugging. 

In JetBrains/Webstorm, it's true that the IDE doesn't follow the map to let you see what's happening in the source to allow debugging. I wouldn't be surprised if VSCode is similar. It's a disadvantage and an advantage as I see it. By only getting the docs and types it does help us see where the docs are inadequate for a dev using Vexflow to know how to use the system. But when the docs aren't up to scratch it's harder to see how to proceed

One thing I wish all projects might do (but we can control Vexflow) is to put a link to the code file at the top in the docs so people can go back to the code if they need it.

**Comment by mscuthbert** [comment]
Seems to work great!  I mean, I do have 10 errors now, but they're all from things that actually changed in Vexflow to VF5,  so they're expected failures.  THANK YOU!
