### ISSUE TITLE
Run eslint before submitting PRs

### ISSUE THREAD

**Issue by ronyeh** [vexflow/vexflow#192]
Hi all,

I've noticed that with a bunch of our PRs, when I run `grunt` to build, I end up with new changes in my repo that I also need to commit after I merge the PR. These changes are introduced by our eslint autofix step of the build process.

Before submitting your next PRs, can you make sure to run a full build and then check in any changes that are introduced by the eslint autofix?

You can also invoke it manually with:

```
grunt eslint
```
or
```
npm run lint
```

Thanks!

Tagging folks who have submitted recent PRs: @mscuthbert @rvilarl @AaronDavidNewman 

Also, there are ways to set up your editor / IDE to run eslint / prettier whenever you save the file. I use VS Code and I have it run on every save.  It should use the `.eslintrc` that is in our vexflow/ directory.

**Comment by mscuthbert** [comment]
My apologies!  I thought that it was running automatically -- OH!  I might have disabled prettier since I wasn't using it in my other projects and I recently did a mass turn-off of plugins to try to make PyCharm faster.  Let's turn this also into an issue:  Github Actions -- reject PRs where eslint fails.

Thanks everyone for indulging my sudden mania to get to the bottom of Formatter!
