### ISSUE TITLE
Error in stavehairpin.ts

### ISSUE THREAD

**Issue by AaronDavidNewman** [vexflow/vexflow#49]
I get the following exception.  Prior versions of vexflow had `notes.first_note `

``` typescript
  const smo390376 = new VF.StaveHairpin({ first_note: smo362522, last_note: smo362522 });
...
    setNotes(notes) {
        if (!notes.firstNote && !notes.lastNote) {
            throw new RuntimeError('BadArguments', 'Hairpin needs to have either firstNote or lastNote set.');
        }
```

**Comment by rvilarl** [comment]
Try

`const smo390376 = new VF.StaveHairpin({ firstNote: smo362522, lastNote: smo362522 }); ...`

**Comment by AaronDavidNewman** [comment]
Would this work for 4.x libraries also?  I'm trying to create code that will run on different libraries for comparison purposes.

**Comment by rvilarl** [comment]
No, there was the decision to change to camel case. In 4.x camel case amd snake case are mixed

**Comment by AaronDavidNewman** [comment]
I didn't realize this decision meant we were breaking every interface.  The old code was pretty consistent, in the sense that shift_x in render_options was always notated that way.  We didn't even add a type that we could use at compile time to determine if there was an issue, it is still just a `Record<string, note>`, and you need to look at the code to know what the right string is.

What would be wrong with:

``` typescript
  setNotes(notes: Record<string, Note>): this {
if (notes['first_note]') notes.firstNote = notes.first_note; // backwards compatibility
```

30 seconds of typing, saves hours possible for a user.  No run-time penalty, you still get the refactoring you want.  win/win.

**Comment by ronyeh** [comment]
Thanks for this discussion.

We will definitely need to figure out [ whether to / how to best  ] support backwards compatibility with v4.

When we went to camelCase, we broke a lot of APIs and we figured it was OK since this is a major major new revision of VexFlow.

However, it you think it will cause people to never want to upgrade (because it's too painful) then we should figure out a good way to support the old APIs with underscores in the strings.

In any case, keep on reporting new issues as you discover them! This will help make the V5 as good a product as possible.

Will you be able to share a landing page where you compare V4 with V5 (assuming we can figure these issues out)?

@rvilarl I think this raises a good question of how much we are breaking during this migration. Will your OSMD / MusicXML app support both V4 and V5? Or will there be an easy way to see both outputs in different tabs so we can flip between them to see the visual difference in the scores?

Perhaps you can archive the V4 version of your app on a different webserver path, so we can compare v4 and v5 easily. That would be awesome.

**Comment by AaronDavidNewman** [comment]
For now I have created a smoosic version that generates the correct identifiers for comparison purposes.  I'm OK with closing this.
