### ISSUE TITLE
Error in ornament

### ISSUE THREAD

**Issue by AaronDavidNewman** [vexflow/vexflow#53]
This worked in Vex 4 libraries.

Uncaught TypeError: Cannot read properties of undefined (reading 'code')

```ts
const smo36378 = new VF.Ornament('mordent_inverted');
```

**Comment by ronyeh** [comment]
Thanks for these reports!

I notice that there are new branches in this repository: https://github.com/vexflow/vexflow/branches

I think it would be cleaner if we could keep the branches in our own personal forks if possible, and avoid pushing directly to this repository. Otherwise, we might get accidental pushes to `main`, or accidentally clobber each others' directories.

I realize this might be a problem if you already have a `vexflow` repository in your own account, since V4 and V5 share the same repo name. @rvilarl and I both renamed our personal V4 repos to `vexflow4`:

https://github.com/ronyeh/vexflow4
https://github.com/rvilarl/vexflow4

That way we could fork this repo and then send in PRs for review/merging (and keep the official repo clear of personal dev branches).

**Comment by ronyeh** [comment]
Can we delete the `issue-58-pr-chordwidth` branch, since it has been merged?

**Comment by ronyeh** [comment]
I don't think this issue has been resolved. It is related to the underscores vs camelCase keys for Ornament.

**Comment by rvilarl** [comment]
> Can we delete the `issue-58-pr-chordwidth` branch, since it has been merged?

Sorry I thought that this was the issue associated with the branch. I will delete the branch and close #58.
