### ISSUE TITLE
Stave section rect needs more internal white space padding all around.

### ISSUE THREAD

**Issue by ronyeh** [vexflow/vexflow#63]
This can be a separate PR, but I think the rect needs more internal padding all around. Right now it crowds the letter B in all 4 directions. :-)

_Originally posted by @ronyeh in https://github.com/vexflow/vexflow/issues/50#issuecomment-1684881222_

**Comment by sschmidTU** [comment]
It would be nice if the padding was configurable though. Because if you want to be as compact as possible, the current version is great.
![pptr-Stave Multiple_Stave_Barline_Test Bravura svg_current](https://user-images.githubusercontent.com/22865285/259218194-63709b07-f2c0-47ee-914b-884e2b498f13.png)

I would probably add a bit of padding by default, but it would be nice to have the compact option as well (for a "compact mode").
